import type { FoodListing } from '../components/map/FoodMarker';

// Mock food listings for testing markers and clustering
export const mockFoodListings: FoodListing[] = [
  // Cluster 1: Downtown area (close together)
  {
    id: '1',
    title: 'Fresh Vegetables Bundle',
    description: 'A variety of fresh seasonal vegetables from my garden including tomatoes, lettuce, and carrots.',
    category: 'vegetables',
    availability: 'high',
    latitude: 37.7849,
    longitude: -122.4094,
    distance: '0.3 km',
    timeLeft: '2 hours',
    isUrgent: true,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop',
    provider: 'Sarah Chen',
    location: 'Downtown SF',
    rating: 4.8,
    reviewCount: 23,
    isVerified: true,
    quantity: '2-3 servings',
    expiresAt: 'today',
  },
  {
    id: '2',
    title: 'Homemade Bread Loaves',
    description: 'Freshly baked sourdough and whole wheat loaves made this morning.',
    category: 'bakery',
    availability: 'medium',
    latitude: 37.7851,
    longitude: -122.4096,
    distance: '0.3 km',
    timeLeft: '1 day',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    provider: 'Mike Johnson',
    location: 'Downtown SF',
    rating: 4.6,
    reviewCount: 15,
    isVerified: true,
    quantity: '2 loaves',
    expiresAt: 'tomorrow',
  },
  {
    id: '3',
    title: 'Organic Apples',
    description: 'Sweet and crispy organic apples from local orchard. Perfect for snacking or baking.',
    category: 'fruits',
    availability: 'high',
    latitude: 37.7847,
    longitude: -122.4092,
    distance: '0.3 km',
    timeLeft: '8 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=300&fit=crop',
    provider: 'Emma Wilson',
    location: 'Downtown SF',
    rating: 4.9,
    reviewCount: 31,
    isVerified: true,
    quantity: '5 lbs',
    expiresAt: 'in 3 days',
  },
  {
    id: '4',
    title: 'Fresh Milk & Cheese',
    description: 'Farm-fresh whole milk and artisanal cheese from local dairy.',
    category: 'dairy',
    availability: 'medium',
    latitude: 37.7853,
    longitude: -122.4098,
    distance: '0.3 km',
    timeLeft: '5 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=400&h=300&fit=crop',
    provider: 'David Martinez',
    location: 'Downtown SF',
    rating: 4.7,
    reviewCount: 18,
    isVerified: false,
    quantity: '1 gallon + cheese',
    expiresAt: 'tomorrow',
  },

  // Cluster 2: Mission District (close together)
  {
    id: '5',
    title: 'Prepared Meals',
    description: 'Healthy homemade meals including vegetarian curry and quinoa salad.',
    category: 'prepared',
    availability: 'medium',
    latitude: 37.7749,
    longitude: -122.4194,
    distance: '0.8 km',
    timeLeft: '3 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    provider: 'Lisa Rodriguez',
    location: 'Mission District',
    rating: 4.5,
    reviewCount: 12,
    isVerified: true,
    quantity: '4 portions',
    expiresAt: 'today',
  },
  {
    id: '6',
    title: 'Sourdough Starter',
    description: 'Active sourdough starter, perfect for making your own bread. Includes instructions.',
    category: 'bakery',
    availability: 'high',
    latitude: 37.7751,
    longitude: -122.4196,
    distance: '0.8 km',
    timeLeft: '6 hours',
    isUrgent: true,
    image: 'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=400&h=300&fit=crop',
    provider: 'Tom Baker',
    location: 'Mission District',
    rating: 4.8,
    reviewCount: 27,
    isVerified: true,
    quantity: '1 jar',
    expiresAt: 'today',
  },
  {
    id: '7',
    title: 'Garden Herbs',
    description: 'Fresh basil, rosemary, thyme, and parsley from my herb garden.',
    category: 'vegetables',
    availability: 'high',
    latitude: 37.7747,
    longitude: -122.4192,
    distance: '0.8 km',
    timeLeft: '12 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop',
    provider: 'Anna Green',
    location: 'Mission District',
    rating: 4.9,
    reviewCount: 35,
    isVerified: true,
    quantity: 'Mixed bundle',
    expiresAt: 'in 2 days',
  },

  // Cluster 3: Castro area (close together)
  {
    id: '8',
    title: 'Fruit Salad Mix',
    description: 'Pre-cut fresh fruit salad with strawberries, pineapple, and grapes.',
    category: 'fruits',
    availability: 'high',
    latitude: 37.7649,
    longitude: -122.4294,
    distance: '1.2 km',
    timeLeft: '6 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=400&h=300&fit=crop',
    provider: 'Carlos Mendez',
    location: 'Castro District',
    rating: 4.4,
    reviewCount: 9,
    isVerified: false,
    quantity: '2 containers',
    expiresAt: 'today',
  },
  {
    id: '9',
    title: 'Yogurt & Kefir',
    description: 'Homemade Greek yogurt and probiotic kefir, great for gut health.',
    category: 'dairy',
    availability: 'low',
    latitude: 37.7651,
    longitude: -122.4296,
    distance: '1.2 km',
    timeLeft: '4 hours',
    isUrgent: true,
    image: 'https://images.unsplash.com/photo-1571212515416-fca0b1bf5b8f?w=400&h=300&fit=crop',
    provider: 'Rachel Kim',
    location: 'Castro District',
    rating: 4.7,
    reviewCount: 14,
    isVerified: true,
    quantity: '2 jars',
    expiresAt: 'today',
  },
  {
    id: '10',
    title: 'Leftover Pizza',
    description: 'Delicious margherita pizza from last night, still fresh and tasty.',
    category: 'prepared',
    availability: 'medium',
    latitude: 37.7647,
    longitude: -122.4292,
    distance: '1.2 km',
    timeLeft: '2 hours',
    isUrgent: true,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=300&fit=crop',
    provider: 'Jake Thompson',
    location: 'Castro District',
    rating: 4.2,
    reviewCount: 6,
    isVerified: false,
    quantity: '4 slices',
    expiresAt: 'today',
  },

  // Individual markers (spread out)
  {
    id: '11',
    title: 'Dairy Products',
    description: 'Various dairy products including butter, cream, and fresh cheese.',
    category: 'dairy',
    availability: 'low',
    latitude: 37.7549,
    longitude: -122.4394,
    distance: '0.5 km',
    timeLeft: '4 hours',
    isUrgent: true,
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=300&fit=crop',
    provider: 'Maria Santos',
    location: 'Sunset District',
    rating: 4.6,
    reviewCount: 11,
    isVerified: true,
    quantity: 'Mixed items',
    expiresAt: 'today',
  },
  {
    id: '12',
    title: 'Seasonal Vegetables',
    description: 'Fresh seasonal vegetables including squash, Brussels sprouts, and kale.',
    category: 'vegetables',
    availability: 'high',
    latitude: 37.7949,
    longitude: -122.3994,
    distance: '1.5 km',
    timeLeft: '8 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1574316071802-0d684efa7bf5?w=400&h=300&fit=crop',
    provider: 'Robert Lee',
    location: 'Richmond District',
    rating: 4.8,
    reviewCount: 22,
    isVerified: true,
    quantity: '3-4 servings',
    expiresAt: 'in 2 days',
  },
  {
    id: '13',
    title: 'Artisan Cookies',
    description: 'Homemade chocolate chip and oatmeal cookies, baked fresh this morning.',
    category: 'bakery',
    availability: 'medium',
    latitude: 37.7599,
    longitude: -122.4344,
    distance: '1.3 km',
    timeLeft: '12 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&h=300&fit=crop',
    provider: 'Sophie Brown',
    location: 'Haight District',
    rating: 4.9,
    reviewCount: 28,
    isVerified: true,
    quantity: '12 cookies',
    expiresAt: 'in 3 days',
  },
  {
    id: '14',
    title: 'Tropical Fruits',
    description: 'Exotic tropical fruits including mango, papaya, and dragon fruit.',
    category: 'fruits',
    availability: 'high',
    latitude: 37.7799,
    longitude: -122.4144,
    distance: '0.7 km',
    timeLeft: '10 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    provider: 'Alex Chen',
    location: 'SOMA',
    rating: 4.5,
    reviewCount: 16,
    isVerified: false,
    quantity: 'Mixed fruits',
    expiresAt: 'in 2 days',
  },
  {
    id: '15',
    title: 'Homemade Soup',
    description: 'Hearty vegetable soup with beans and fresh herbs, perfect for cold weather.',
    category: 'prepared',
    availability: 'medium',
    latitude: 37.7699,
    longitude: -122.4244,
    distance: '1.0 km',
    timeLeft: '5 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',
    provider: 'Jennifer Davis',
    location: 'Noe Valley',
    rating: 4.7,
    reviewCount: 19,
    isVerified: true,
    quantity: '4 servings',
    expiresAt: 'tomorrow',
  },

  // Additional cluster for testing
  {
    id: '16',
    title: 'Fresh Basil',
    description: 'Aromatic fresh basil leaves, perfect for pasta, pizza, or pesto.',
    category: 'vegetables',
    availability: 'high',
    latitude: 37.7850,
    longitude: -122.4095,
    distance: '0.3 km',
    timeLeft: '4 hours',
    isUrgent: false,
    image: 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=400&h=300&fit=crop',
    provider: 'Marco Rossi',
    location: 'Downtown SF',
    rating: 4.8,
    reviewCount: 13,
    isVerified: true,
    quantity: '1 bunch',
    expiresAt: 'in 2 days',
  },
  {
    id: '17',
    title: 'Croissants',
    description: 'Buttery, flaky croissants made with French technique. Best enjoyed warm.',
    category: 'bakery',
    availability: 'medium',
    latitude: 37.7848,
    longitude: -122.4093,
    distance: '0.3 km',
    timeLeft: '3 hours',
    isUrgent: true,
    image: 'https://images.unsplash.com/photo-1555507036-ab794f4ade2a?w=400&h=300&fit=crop',
    provider: 'Pierre Dubois',
    location: 'Downtown SF',
    rating: 4.9,
    reviewCount: 41,
    isVerified: true,
    quantity: '6 croissants',
    expiresAt: 'today',
  },
];